---
- include_tasks: setup.yml
  when: ansible_os_family == 'Debian'

- name: Install Filebeat.
  package:
    name: "{{ filebeat_package }}"
    state: "{{ filebeat_package_state }}"

- include_tasks: config.yml
  when: filebeat_create_config | bool

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: filebeat
    state: started
    enabled: true
