---
filebeat_version: 8.x
filebeat_package: filebeat
filebeat_package_state: present

filebeat_create_config: true
filebeat_template: "filebeat.yml"

filebeat_inputs:
  - type: log
    paths:
      - "/var/log/iptables.log"

filebeat_output_elasticsearch_enabled: true
filebeat_output_elasticsearch_hosts:
  - "81.177.165.73:9200"

filebeat_output_elasticsearch_auth:
    username: "elastic"
    password: "task12112022"

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "81.177.165.73:5044"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log


